# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjE5YmJhNDgwYzcwZjhmMzVjMzlkNjY2MjQ0NGNlNmY4MGQwZTkzZGZhZWUxMzMzMWJhY2EyOTcwZWEzNzFiM2RhY2ZkMTg1N2IwNGY1NGI5MDVkMzlkZTllMmJkYWM3MTQ1Y2I4NDQxM2JhZWNkN2IzMjQxNTFkMTgwMTJhM2U=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
